image: docker:stable

stages:
  - test
  - package
  - release

variables:
  STAGING_REGISTRY: "registry.gitlab.com"
  CONTAINER_TEST_IMAGE: ${STAGING_REGISTRY}/bigdataboutique/${CI_PROJECT_NAME}:commit-${CI_COMMIT_SHA}

services:
  - name: docker:dind
    command: ["--experimental"]

static-analysis:
  stage: test
  image: node:14.18.2
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - admin-frontend/node_modules
      - backend/node_modules
  script:
    # These are in () to run in a subshell and not modify the real pwd
    - (cd admin-frontend && npm install)
    - (cd backend && npm install)
    - npm run prettier-check
    - npm run lint
    - npm run test
  only:
    changes:
      - Dockerfile
      - backend/**/*
      - admin-frontend/**/*

package:
  stage: package
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $STAGING_REGISTRY
  script:
    - docker build --squash -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    changes:
      - Dockerfile
      - backend/**/*
      - admin-frontend/**/*

release:
  stage: release
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $STAGING_REGISTRY
  script:
    - IMAGE_NAME=${STAGING_REGISTRY}/bigdataboutique/${CI_PROJECT_NAME}:`date '+%Y-%m-%d-%H%M'`-${CI_COMMIT_SHA:0:9}
    - echo $IMAGE_NAME
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $IMAGE_NAME
    - docker push $IMAGE_NAME
    - docker tag $CONTAINER_TEST_IMAGE ${STAGING_REGISTRY}/bigdataboutique/${CI_PROJECT_NAME}:latest
    - docker push ${STAGING_REGISTRY}/bigdataboutique/${CI_PROJECT_NAME}:latest
  only:
    refs:
      - master
    changes:
      - Dockerfile
      - backend/**/*
      - admin-frontend/**/*

dockerhub:
  stage: release
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $STAGING_REGISTRY
    - docker login -u $DOCKERHUB_USER -p "$DOCKERHUB_PASSWORD" docker.io
  script:
    - IMAGE_NAME=bigdataboutique/elastiquill:${CI_COMMIT_TAG}
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $IMAGE_NAME
    - docker push $IMAGE_NAME
    - docker tag $CONTAINER_TEST_IMAGE bigdataboutique/elastiquill:latest
    - docker push bigdataboutique/elastiquill:latest
  only:
    - /^v.*$/
  except:
    - branches
