image: docker:stable

stages:
  - package
  - release

variables:
  STAGING_REGISTRY: "registry.gitlab.com"
  CONTAINER_TEST_IMAGE: ${STAGING_REGISTRY}/bigdataboutique/${CI_PROJECT_NAME}:commit-${CI_COMMIT_SHA}
  
services:
  - name: docker:dind
    command: ["--experimental"]
  
before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $STAGING_REGISTRY

package:
  stage: package
  script:
    - docker build --squash -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

release:
  stage: release
  variables:
    GIT_STRATEGY: none
  script:
    - IMAGE_NAME=${STAGING_REGISTRY}/bigdataboutique/${CI_PROJECT_NAME}:`date '+%Y-%m-%d-%H%M'`-${CI_COMMIT_SHA:0:9}
    - echo $IMAGE_NAME
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $IMAGE_NAME
    - docker push $IMAGE_NAME
    - docker tag $CONTAINER_TEST_IMAGE ${STAGING_REGISTRY}/bigdataboutique/${CI_PROJECT_NAME}:latest
    - docker push ${STAGING_REGISTRY}/bigdataboutique/${CI_PROJECT_NAME}:latest
  only:
    - master
    
dockerhub:
  stage: release
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $STAGING_REGISTRY
    - docker login -u $DOCKERHUB_USER -p "$DOCKERHUB_PASSWORD" docker.io
  script:
    - IMAGE_NAME=bigdataboutique/elastiquill:v${CI_COMMIT_TAG}
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $IMAGE_NAME
    - docker push $IMAGE_NAME
    - docker tag $CONTAINER_TEST_IMAGE bigdataboutique/elastiquill:latest
    - docker push bigdataboutique/elastiquill:latest
  only:
    - /^v.*$/
  except:
    - branches