version: "3.3"

services:
  blog_es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: blog_es
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200

  blog_kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: blog_kibana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
    environment:
      ELASTICSEARCH_HOSTS: http://blog_es:9200
    ports:
      - 5601:5601

  blog:
    image: bigdataboutique/elastiquill
    container_name: blog
    environment:
      ELASTICSEARCH_HOSTS: http://blog_es:9200
      BLOG_ADMIN_EMAILS: _all_
      #BLOG_THEME_PATH: /etc/elastiquill-theme
      BLOG_THEME_CACHING: "false"
      BLOG_CACHE_TTL: "0"
    depends_on:
      - blog_es
    ports:
      - 5000:5000
    volumes:
      - ${PWD}/_k8s:/etc/elastiquill
      #- ${PWD}/_theme:/etc/elastiquill-theme

networks:
  default:
    external:
      name: blog
