apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: elastiquill
  name: elastiquill
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elastiquill
  template:
    metadata:
      labels:
        app: elastiquill
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - elastiquill
              topologyKey: kubernetes.io/hostname
      containers:
      - image: bigdataboutique/elastiquill
        name: elastiquill
        volumeMounts:
        - name: elastiquill-config
          mountPath: /etc/elastiquill
          readOnly: true
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
      volumes:
      - name: elastiquill-config
        secret:
          secretName: elastiquill-demo-config
---
apiVersion: v1
kind: Service
metadata:
  name: elastiquill
  namespace: default
spec:
  ports:
  - name: elastiquill
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: elastiquill
  type: LoadBalancer