apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elastiquill
  name: elastiquill
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elastiquill
  template:
    metadata:
      labels:
        app: elastiquill
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - elastiquill
              topologyKey: kubernetes.io/hostname
#      initContainers:
#      - name: git-theme-init-sync
#        image: k8s.gcr.io/git-sync:v3.1.1
#        volumeMounts:
#        - name: theme
#          mountPath: /etc/elastiquill-theme
#        env:
#        - name: GIT_SYNC_REPO
#          value: <your theme git repo>
#        - name: GIT_SYNC_BRANCH
#          value: master
#        - name: GIT_SYNC_ROOT
#          value: /etc/elastiquill-theme
#        - name: GIT_SYNC_DEST
#          value: theme
#        - name: GIT_SYNC_PERMISSIONS
#          value: "0777"
#        - name: GIT_SYNC_ONE_TIME
#          value: "true"
#        - name: GIT_SYNC_SSH
#          value: "false"
#        securityContext:
#          runAsUser: 0
      containers:
      - image: bigdataboutique/elastiquill:latest
        imagePullPolicy: Always
        name: elastiquill
#        env:
#        - name: BLOG_THEME_PATH
#          value: /etc/elastiquill-theme/theme
        volumeMounts:
        - name: elastiquill-config
          mountPath: /etc/elastiquill
          readOnly: true
        - name: theme
          mountPath: /etc/elastiquill-theme
          readOnly: true
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
      volumes:
      - name: theme
        emptyDir: {}
      - name: elastiquill-config
        secret:
          secretName: elastiquill-demo-config
---
apiVersion: v1
kind: Service
metadata:
  name: elastiquill
  namespace: default
spec:
  ports:
  - name: elastiquill
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: elastiquill
  type: NodePort
